package StudentPanels;

import Frames.StudentJFrame;
import static StudentPanels.Database.connectDB;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Emily Anas
 */
public class SReturn extends javax.swing.JPanel {

    private static Timestamp sts;
    private static String barcode, retDate;

    /**
     * @return the sts
     */
    public static Timestamp getSts() {
        return sts;
    }

    /**
     * @return the barcode
     */
    public static String getBarcode() {
        return barcode;
    }

    /**
     * @return the retDate
     */
    public static String getRetDate() {
        return retDate;
    }
    JPanel home;

    /**
     * Creates new form SSignOut
     */
    public SReturn() {
        initComponents();
    }

    public SReturn(JPanel p) {
        initComponents();
        home = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        tfBarcode = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeader.setText("Please scan the barcode of the item you would like to return");

        tfBarcode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnReturn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(tfBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(btnReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHeader)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGap(240, 240, 240)
                .addComponent(tfBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //back brings them to menu
        CardLayout cl = (CardLayout) home.getLayout();
        cl.show(home, "menu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        //get barcode and id the item is being returned under
        barcode = tfBarcode.getText();
        String id = SLogin.getid();
        
        //timestamp formatting stuff
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        Date now = new Date(cal.getTimeInMillis());
        retDate = df.format(cal.getTime());
        sts = new Timestamp(now.getTime());
        Timestamp rts = new Timestamp(0, 0, 0, 0, 0, 0, 0);

        //conect to database
        Connection c = connectDB();
        if (c == null) {
            System.exit(-1);
        }
        Statement stmt;
        try {
            stmt = c.createStatement();
            //find where return is "null" and student and item match, and fix the return date
            String q = ("UPDATE history SET return_date = '" + getSts() + "' WHERE return_date = '" + rts + "' AND s_id = '" + id + "' AND i_bc = '" + getBarcode() + "'");
            PreparedStatement pstmt = c.prepareStatement(q);
            {
                pstmt.executeUpdate();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Something went wrong trying to return an item", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
        //bring them to the confirmation screen
        CardLayout cl = (CardLayout) home.getLayout();
        StudentJFrame topFrame = (StudentJFrame) SwingUtilities.getWindowAncestor(this);
        topFrame.src.RetCongratsInit();
        tfBarcode.setText("");
        cl.show(home, "retcongrats");
    }//GEN-LAST:event_btnReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField tfBarcode;
    // End of variables declaration//GEN-END:variables
}
