package StudentPanels;

import static StudentPanels.Database.connectDB;
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Calendar;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Emily Anas
 */
public class SReturn extends javax.swing.JPanel {

    JPanel home;

    /**
     * Creates new form SSignOut
     */
    public SReturn() {
        initComponents();
    }

    public SReturn(JPanel p) {
        initComponents();
        home = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        tfBarcode = new javax.swing.JTextField();
        btnReturn = new javax.swing.JButton();

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeader.setText("Please scan the barcode of the item you would like to return");

        tfBarcode.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnReturn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(tfBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(btnReturn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHeader)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addGap(240, 240, 240)
                .addComponent(tfBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout cl = (CardLayout) home.getLayout();
        cl.show(home, "menu");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        String barcode = tfBarcode.getText();
        String id = SLogin.getid();
        //DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        Date now = new Date(cal.getTimeInMillis());
        //String sodate = df.format(cal.getTime());
        Timestamp sts = new Timestamp(now.getTime());
        Timestamp rts = new Timestamp(0, 0, 0, 0, 0, 0, 0);

        Connection c = connectDB();
        if (c == null) {
            System.exit(-1);
        }
        Statement stmt;
        ResultSet rs;
        //int text text boolean
        try {
            stmt = c.createStatement();
            rs = stmt.executeQuery("SELECT * FROM history");
            // Now do something with the ResultSet .... 
            while (rs.next() == true) {
                if (rs.getTimestamp("return_date") == rts) {
                    if (rs.getString("s_id").equals(id)) {
                        if (rs.getString("i_bc").equals(barcode)) {
                            try {
                                stmt = c.createStatement();
                                String q = ("UPDATE history SET return_date = ? WHERE column_5 = " + item + " LIMIT 1");
                                PreparedStatement pstmt = c.prepareStatement(q);
                                {
                                    pstmt.setBoolean(1, false);
                                    pstmt.executeUpdate();
                                    System.out.println("Boop");
                                }
                            } catch (SQLException e) {
                                System.out.println(e.getMessage() + "\nrip");
                            }
                        }
                    }
                }

                //System.out.println(rs.getObject(1));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage() + "\nrip");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField tfBarcode;
    // End of variables declaration//GEN-END:variables
}
