package TeacherPanels;

import java.awt.CardLayout;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 072584980
 */
public class TPickStudent extends javax.swing.JPanel {
JPanel home;

    /**
     * Creates new form TMenu
     */
    public TPickStudent() {
        initComponents();
    }
    public TPickStudent(JPanel p) {
        initComponents();
        home = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblHeader = new javax.swing.JLabel();
        tfFName = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        tfStudentNum = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        tfLName = new javax.swing.JLabel();
        lblStudentNum = new javax.swing.JLabel();
        btnFindStudName = new javax.swing.JButton();
        btnFindStudNum = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblByName = new javax.swing.JLabel();
        lblByNum = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 750));

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeader.setText("Please provide either a name or a student number");

        tfFName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tfStudentNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfStudentNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentNumActionPerformed(evt);
            }
        });

        lblFName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFName.setText("First name");

        tfLName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfLName.setText("Last name");

        lblStudentNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblStudentNum.setText("Student #");

        btnFindStudName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFindStudName.setText("Find student");
        btnFindStudName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStudNameActionPerformed(evt);
            }
        });

        btnFindStudNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFindStudNum.setText("Find student");
        btnFindStudNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindStudNumActionPerformed(evt);
            }
        });

        lblByName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblByName.setText("By name");

        lblByNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblByNum.setText("By student number");

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(lblHeader)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(lblFName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfLName)
                .addGap(363, 363, 363))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFindStudName)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(tfStudentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219)
                        .addComponent(btnFindStudNum))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblByName)
                            .addComponent(lblByNum)
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(lblStudentNum)))
                .addGap(15, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblByName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindStudName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFName)
                    .addComponent(tfLName))
                .addGap(68, 68, 68)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblByNum)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStudentNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindStudNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentNum)
                .addGap(157, 157, 157)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfStudentNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentNumActionPerformed

    private void btnFindStudNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStudNameActionPerformed
        //history of student with first name tfFName.getText() and last name tfLName.getText()
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindStudNameActionPerformed

    private void btnFindStudNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindStudNumActionPerformed
        //history of student with id tfBarcode.getText()
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindStudNumActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout cl = (CardLayout) home.getLayout();
        cl.show(home, "menu");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFindStudName;
    private javax.swing.JButton btnFindStudNum;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblByName;
    private javax.swing.JLabel lblByNum;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblStudentNum;
    private javax.swing.JTextField tfFName;
    private javax.swing.JLabel tfLName;
    private javax.swing.JTextField tfStudentNum;
    // End of variables declaration//GEN-END:variables
}
