
import static StudentPanels.Database.connectDB;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emily Anas
 */
public class TAddStudentForm extends javax.swing.JPanel {

    /**
     * Creates new form TAddStudentForm
     */
    public TAddStudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Add Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton1)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jButton1)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {                                         
            File file = new File("StudentInfoStuffs.txt");
            Scanner sc = new Scanner(file);
            Connection c = connectDB();
            if (c == null)
                System.exit(-1);
            Statement stmt;
            ResultSet rs;
            //data types are: int text text boolean
            while(sc.hasNext()){
            try {
                stmt = c.createStatement();
                rs = stmt.executeQuery("SELECT * FROM student");
                String q = "insert into student(id,fname,lname,active) values(?,?,?,?)";
                String ln = sc.nextLine();
                String [] info = ln.split(",");
                PreparedStatement pstmt = c.prepareStatement(q); {
                pstmt.setString(1, info[0]);
                pstmt.setString(2, info[1]);
                pstmt.setString(3, info[2]);
                pstmt.setBoolean(4, true);
                pstmt.executeUpdate();
                System.out.println("Boop");
            }} catch (SQLException e) {
                System.out.println(e.getMessage()+"\n rip");
            }}
            System.out.println("Done");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TAddStudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
